### ISSUE TITLE
Gender

### ISSUE THREAD

**Issue by signalwerk** [jwssnr/feeef2#16]
Hallo @jwssnr 
Darf ich dich beten auch im github-Repo noch die feminine (Frontend-Entwickler/in) Version für FE zu ergänzen:

> ![image](https://user-images.githubusercontent.com/992878/47418354-3df13500-d77a-11e8-93a1-fbca155b79e1.png)

**Comment by jwssnr** [comment]
… done. Bei den Grafiken mach ichs dann auch noch bei Gelgenheit.

**Comment by signalwerk** [comment]
Merci @jwssnr
