### ISSUE TITLE
ownership

### ISSUE THREAD

**Issue by signalwerk** [jwssnr/feeef2#6]
I don't wanna take away anything from you or offend you. But since this repo is right now in your private account it might look not that serious. Probably we could create a new github-organisation. and of course you would still be the holder of the repo. 

Please don't get me wrong. I really appreciate your effort and I think it's a great idea!

**Comment by jwssnr** [comment]
you’re right. but let’s wait for the first feedback from «ICT» during the next weeks.

**Comment by signalwerk** [comment]
@jwssnr sure! let's keep it in the back of our mind and I'll close the issue for now
