### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by signalwerk** [jwssnr/feeef2#8]
Hey @jwssnr 
Kannst du allenfalls das Wiki hier bei Github öffentlich machen oder mich ins Team dieses Repositories als Member aufnehmen. Ich möchte gerne zwei/drei links ablegen, die uns allenfalls später helfen könnten:

* [Digitalisierung in der Berufsbildung](https://berufsbildungdigital.ch/)
* [Anforderungsprofile für Berufsbilder](http://www.anforderungsprofile.ch/)

**Comment by jwssnr** [comment]
Hoi Stefan

Funktioniert das so?
https://github.com/jwssnr/feeef2/invitations

Grüsse
Jürgen



=============================
Jürgen Wössner
Typograf und Frontend-Entwickler
Tannenbergstrasse 14, 9032 Engelburg
079 821 12 10
https://j.wssnr.ch 
====================
Projekt: https://frontend-entwickler.ch
===========



Am 30.06.2018 um 20:49 schrieb Stefan Huber <notifications@github.com>:

Hey @jwssnr
Kannst du allenfalls das Wiki hier bei Github öffentlich machen oder mich ins Team dieses Repositories als Member aufnehmen. Ich möchte gerne zwei/drei links ablegen, die uns allenfalls später helfen könnten:

	• Digitalisierung in der Berufsbildung
	• Anforderungsprofile für Berufsbilder

**Comment by signalwerk** [comment]
perfekt. ich habe die links da mal abgelegt ohne grosses drumrum...
